version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    security-updates-only: false
    labels:
      - "dependencies"
      - "python"
    versioning-strategy:
      increase-if-necessary: true
      lockfile-only: false
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
      aws-dependencies:
        patterns:
          - "boto3*"
          - "botocore"
      db-dependencies:
        patterns:
          - "psycopg2*"
          - "redis*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    # Configure commit message style
    commit-message:
      prefix: "ci"
      include: "scope"